[package]
name = "rust-webgl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
js-sys = "0.3.64"
log = "0.4.20"
serde = "1.0.188"
serde-wasm-bindgen = "0.5.0"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = ["CanvasRenderingContext2d", "HtmlCanvasElement", "Window", "Document", "CssStyleDeclaration", "WebGl2RenderingContext", "WebGlProgram", "WebGlShader", "WebGlBuffer", "WebGlVertexArrayObject", "WebGlActiveInfo"] }
