[package]
name = "rust-rig"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
dotenvy = "0.15.7"
regex = "1.12.3"
rig-core = "0.30.0"
rig-postgres = "0.1.31"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio"] }
tempdir = "0.3.7"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
