[package]
name = "rust-pixels"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
log = "0.4.22"
pixels = "0.13.0"
winit = { version = "0.30.4", features = ["rwh_05"] }

