[package]
name = "rust-wgpu-winit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
log = "0.4.22"
tokio = { version = "1.39.2", features = ["full"] }
wgpu = "22.1.0"
winit = { version = "0.30.5" }
