[package]
name = "app_sdl3"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = { path = "../lib" }
color-eyre = "0.6.3"
sdl3 = { version = "0.14.25", features = ["ttf", "build-from-source", "image"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
bytemuck = "1.22.0"
