[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = { path = "../lib" }
binpack2d = "1.0.1"
bytemuck = { version = "1.22.0", features = ["derive"] }
color-eyre = "0.6.3"
futures = "0.3.31"
glam = { version = "0.30.1", features = ["bytemuck"] }
image = "0.25.6"
rand = "0.9.0"
rusttype = "0.9.3"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
wgpu = "25.0.0"
winit = "0.30.9"

[target.'cfg(target_family = "wasm")'.dependencies]
console_error_panic_hook = "0.1.7"
