[package]
name = "robowar"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "0.10.1"
num = "0.4.3"
rand = "0.9.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
