[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.214", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v7"] }
web-time = "1.1.0"
