[package]
name = "rust-webgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../lib" }
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
bytemuck = { version = "1.20.0", features = ["derive"] }
gloo = "0.11.0"
js-sys = "0.3.72"
log = "0.4.22"
nalgebra = { version = "0.33.1", features = ["bytemuck"] }
nalgebra-glm = "0.19.0"
serde = "1.0.213"
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.132"
wasm-bindgen-futures = "0.4.45"
web-sys = { version = "0.3.72", features = [
	"HtmlCanvasElement",
	"CssStyleDeclaration",
	"WebGl2RenderingContext",
	"WebGlBuffer",
	"WebGlProgram",
	"WebGlActiveInfo",
	"WebGlShader",
	"WebGlUniformLocation",
	"KeyboardEvent",
	"MouseEvent",
] }
rusttype = "0.9.3"
