[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies.lib]
path = "../lib"

[dependencies]
rand = "0.8.5"
futures = "0.3.26"
vek = "0.15.10"
gloo-console = "0.2.3"
memoffset = "0.8"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.84"

[dependencies.web-sys]
version = "0.3.61"
features = [
	"WebGl2RenderingContext",
	"CanvasRenderingContext2d",
]

[dependencies.getrandom]
version = "0.2.8"
features = [
	"js",
]

[dependencies.async-std]
version = "1.12.0"
features = [
	"attributes",
]
