[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.183"
serde_json = "1.0.105"
tokio = { version = "1.31.0", features = ["full", "time"] }
shared = { path = "../shared" }
axum = { version = "0.6.20", features = ["macros", "ws", "headers", "tokio"] }
tower-http = { version = "0.4.3", features = ["cors", "trace"] }
tower = "0.4.13"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.4.1", features = ["v4"] }
chrono = "0.4.26"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.7"
futures = "0.3.28"
