[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = "1.0.183"
serde_json = "1.0.105"
tokio = "1.31.0"
shared = { path = "../shared" }