[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
serde = "1.0.152"
serde_json = "1.0.93"
async-std = "1.12.0"
base64 = "0.21.0"
log = "0.4.17"
simplelog = "0.12.0"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = [
	"json"
]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = [
	"tera",
]

[dependencies.sqlx]
version = "0.6.2"
features = [
	"runtime-async-std-native-tls",
	"sqlite"
]
